### ISSUE TITLE
Hello there

### ISSUE THREAD

**Issue by anishjajodia** [julesmoretti/fancrawl#2]
Hello there,

While searching for the same, I found this app. Does this online web-app work perfectly in case of unfollowing people?

Do we also have a specified CURL setup, so that it does automatically after instagram's spam thing is done? i.e. 50 after 10 mins?

**Comment by julesmoretti** [comment]
Hello Aneeshjajodia:

Perfectly... that improbably due to the nature of writing code. I am sure their are bugs, but so far it has done the job rather well. You can check out my IG account jules_moretti.

I am not sure I understand your second question. Instagram does kick the system off everytime it detects that it is being too aggressive. This is still happening despite following way bellow 100 per hour... When that happens though you have to go to your instagram account manually and input a patcha before being able to restart FanCrawl... What does that the CURL setup does?

Sorry for the delay by the way!
